done css for contacts
Okimmi/project-web-wizards pull request #14
Opened 2023-05-20 21:47 UTC by Softmaks

--first-btnlink-color: #9DC262;
  --second-btnlink-color:#FFFFFF;

2023-05-20 21:49 UTC, Softmaks commented
Добавь, пожалуйста, в css\styles.css две строчки:

  --first-btnlink-color: #9DC262;
  --second-btnlink-color:#FFFFFF;

2023-05-21 05:35 UTC, Okimmi requested changes

2023-05-21 05:35 UTC, Okimmi commented on src/css/basic.css
Чому видалнний Basic.css?

2023-05-21 07:33 UTC, Softmaks commented on src/css/basic.css
Я менял там случайно одно значение в файле Basic и потом обратно его вернул. Гит понял это как изменение и захотел его проинтегрировать в мейн, я дабы ничего не сломать удалил файл со своей стороны полностью.

2023-05-21 08:32 UTC, Okimmi requested changes

2023-05-21 08:32 UTC, Okimmi commented on src/css/contacts.css
> +    min-height: 480px;
В мобільній версії інша висота картинки

2023-05-21 08:32 UTC, Okimmi commented on src/css/basic.css
Ок. Але щоб не комітити чогось то в git desktop можна вибирати зміни які не хочеш комітити

2023-05-21 08:32 UTC, Okimmi commented on src/css/contacts.css
> +@media only screen and (min-width: 768) {
Не має px

2023-05-21 08:45 UTC, Softmaks commented on src/css/basic.css
Пішов дивитись Репету )

2023-05-21 08:48 UTC, Okimmi commented on src/css/basic.css
Можеш залишити як є, я це виправлю. На зустрічі покажу як робити :)

2023-05-21 08:58 UTC, Softmaks commented on src/css/contacts.css
> +    min-height: 480px;
то э так 

І змінив на корректні значення у блоці /* For Tablet sizes img */

2023-05-21 08:59 UTC, Okimmi approved these changes

2023-05-21 08:59 UTC, Softmaks commented on src/css/contacts.css
> +@media only screen and (min-width: 768) {
Обожнюю такі штуки.
Дякую, виправив

2023-05-21 09:09 UTC, Okimmi approved these changes

2023-05-21 09:09 UTC, merged