how-it-works
Okimmi/project-web-wizards pull request #3
Opened 2023-05-18 18:16 UTC by OlenaKliuchka

2023-05-18 22:07 UTC, Okimmi requested changes

2023-05-18 22:07 UTC, Okimmi commented on src/partials/how-it-works.html
> +            <h3 class="title-wrapper">FIrst Step</h3>
Велика "і" замість маленької. Має бути F**i**rst Step.

2023-05-19 05:59 UTC, OlenaKliuchka commented on src/partials/how-it-works.html
> +            <h3 class="title-wrapper">FIrst Step</h3>
Виправила

2023-05-19 06:01 UTC, Okimmi approved these changes

2023-05-19 06:01 UTC, merged