your-order-modal html
Okimmi/project-web-wizards pull request #4
Opened 2023-05-18 18:55 UTC by Lunatickus

2023-05-18 22:39 UTC, Okimmi requested changes

2023-05-18 22:39 UTC, Okimmi commented on src/partials/your-order-modal.html
> +              ./img/your-order-modal/img-2_tab@1x.png 2x
Невірний шлях до картинки. Має бути ./img/your-order-modal/img-2_tab@**2**x.png

2023-05-18 22:39 UTC, Okimmi commented on src/partials/your-order-modal.html
> +              ./img/your-order-modal/img-3_tab@1x.png 2x
Невірний шлях до картинки. Має бути  ./img/your-order-modal/img-3_tab@**2**x.png

2023-05-18 22:39 UTC, Okimmi commented on src/partials/your-order-modal.html
> +              width="133"
В тег <source> не можна задавати розмір.

2023-05-18 22:39 UTC, Okimmi commented on src/partials/your-order-modal.html
> +              height="148"
В тег <source> не можна задавати розмір.

2023-05-18 22:39 UTC, Okimmi commented on src/partials/your-order-modal.html
> +              width="172"
В тег <source> не можна задавати розмір.

2023-05-18 22:39 UTC, Okimmi commented on src/partials/your-order-modal.html
> +              height="148"
В тег <source> не можна задавати розмір.

2023-05-18 22:39 UTC, Okimmi commented on src/partials/your-order-modal.html
> +              width="172"
В тег <source> не можна задавати розмір.

2023-05-18 22:39 UTC, Okimmi commented on src/partials/your-order-modal.html
> +              height="148"
В тег <source> не можна задавати розмір.

2023-05-19 08:41 UTC, Lunatickus commented on src/partials/your-order-modal.html
> +              ./img/your-order-modal/img-2_tab@1x.png 2x
Исправлено

2023-05-19 08:41 UTC, Lunatickus commented on src/partials/your-order-modal.html
> +              ./img/your-order-modal/img-3_tab@1x.png 2x
Исправлено

2023-05-19 08:41 UTC, Lunatickus commented on src/partials/your-order-modal.html
> +              width="133"
Исправлено

2023-05-19 08:41 UTC, Lunatickus commented on src/partials/your-order-modal.html
> +              height="148"
Исправлено

2023-05-19 08:42 UTC, Lunatickus commented on src/partials/your-order-modal.html
> +              width="172"
Исправлено

2023-05-19 08:42 UTC, Lunatickus commented on src/partials/your-order-modal.html
> +              height="148"
Исправлено

2023-05-19 09:09 UTC, Okimmi approved these changes

2023-05-19 09:09 UTC, merged